"""One monitored NVIDIA DirectML request. Developer tool; no batching or CPU backend retry.
Input JSON: {"request": <Probe.Request>, "tensors": <optional frozen tensors>}.
Optional reference is a prior Probe.Result JSON (not generated by this tool).
"""
import argparse
import ctypes
from ctypes import wintypes
import hashlib
import json
from pathlib import Path
import subprocess
import sys
import time


class Memory(ctypes.Structure):
    _fields_ = [("length", wintypes.DWORD), ("load", wintypes.DWORD)] + [(name, ctypes.c_ulonglong) for name in
        ("totalPhysical", "freePhysical", "totalPageFile", "freePageFile", "totalVirtual", "freeVirtual", "freeExtended")]


def memory():
    data = Memory()
    data.length = ctypes.sizeof(data)
    if not ctypes.windll.kernel32.GlobalMemoryStatusEx(ctypes.byref(data)):
        raise OSError("Cannot measure system memory")
    return {"freeMiB": round(data.freePhysical / 1048576), "freeCommitMiB": round(data.freePageFile / 1048576)}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("model", type=Path)
    parser.add_argument("request", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--adapter", type=int, required=True, help="DXGI index, NOT nvidia-smi index")
    parser.add_argument("--reference", type=Path)
    parser.add_argument("--export-features", action="store_true", help="Explicit developer-only frozen encoder feature export; never use private filenames as public training data")
    parser.add_argument("--probe", type=Path, default=Path("tests/DeskNest.DirectMLProbe/bin/Release/net10.0/DeskNest.DirectMLProbe.exe"))
    args = parser.parse_args()
    if sys.platform != "win32":
        parser.error("This NVIDIA DirectML check requires Windows")
    data = args.request.read_bytes()
    if len(data) > 1024 * 1024:
        raise ValueError("Input exceeds 1 MiB")
    request = json.loads(data)["request"]
    args.output.mkdir(parents=True, exist_ok=False)
    process = None
    samples = []
    summary = {"success": False, "scope": __doc__, "adapterDxgiIndex": args.adapter,
               "requestSha256": hashlib.sha256(data).hexdigest(), "initialHost": memory(),
               "gpuPeakMemoryMeasured": False, "formalAcceptance": False}
    probe = args.probe.resolve(strict=True)
    summary["probeAssemblySha256"] = hashlib.sha256(probe.with_suffix(".dll").read_bytes()).hexdigest()
    try:
        if summary["initialHost"]["freeCommitMiB"] < 2048:
            raise RuntimeError("Insufficient committed-memory headroom for one GPU load")
        with (args.output / "stdout.json").open("xb") as stdout, (args.output / "stderr.log").open("xb") as stderr:
            command = [str(probe), str(args.model.resolve(strict=True)), str(args.adapter), str((args.output / "profiles").resolve())]
            if args.export_features:
                command.append("--export-features")
            process = subprocess.Popen(command, stdin=subprocess.PIPE,
                stdout=stdout, stderr=stderr, creationflags=subprocess.BELOW_NORMAL_PRIORITY_CLASS)
            process.stdin.write(data)
            process.stdin.close()
            started = time.monotonic()
            while process.poll() is None:
                host = memory()
                samples.append({"elapsedMs": round((time.monotonic() - started) * 1000), **host})
                if host["freeMiB"] < 192 or host["freeCommitMiB"] < 768:
                    raise RuntimeError("Emergency low memory: terminate only this probe")
                if time.monotonic() - started > 90:
                    raise TimeoutError("One request exceeded 90 seconds; no CPU retry")
                time.sleep(0.1)
        summary["exitCode"] = process.returncode
        if process.returncode != 0:
            raise RuntimeError("DirectML request failed; retained stderr, no CPU retry")
        measured = json.loads((args.output / "stdout.json").read_text(encoding="utf-8"))
        if measured["success"] is not True or measured["provider"] != "DirectML" or measured["adapter"]["vendorId"] != 0x10DE:
            raise ValueError("Missing NVIDIA DirectML execution evidence")
        if args.export_features and measured.get("featuresExported") is not True:
            raise ValueError("Requested feature export was not reported")
        result = measured["result"]
        if result["requestId"] != request["requestId"] or result["revision"] != request["revision"]:
            raise ValueError("Request/reply mismatch")
        if args.reference:
            expected = json.loads(args.reference.read_text(encoding="utf-8"))
            if result["tensors"] != expected["tensors"]:
                raise ValueError("Token tensors differ from the supplied reference")
            logit_delta = max(abs(a - b) for a, b in zip(result["logits"], expected["logits"], strict=True))
            probability_delta = max(abs(a - b) for a, b in zip(result["probabilities"], expected["probabilities"], strict=True))
            if logit_delta > 1e-4 or probability_delta > 1e-4 or result["choice"] != expected["choice"] or result["action"] != expected["action"]:
                raise ValueError("DirectML result differs from supplied numerical/routing reference")
            summary.update(referenceSha256=hashlib.sha256(args.reference.read_bytes()).hexdigest(),
                           maxReferenceLogitDelta=logit_delta, maxReferenceProbabilityDelta=probability_delta)
        summary.update(success=True, adapter=measured["adapter"], inputMode=measured["inputMode"],
                       modelManifestSha256=measured["modelManifestSha256"], totalMs=measured["totalMs"],
                       hostPeakWorkingSetMiB=round(measured["hostPeakWorkingSetBytes"] / 1048576),
                       choice=result["choice"], action=result["action"])
    except BaseException as error:
        summary["error"] = type(error).__name__ + ": " + str(error)
    finally:
        if process is not None and process.poll() is None:
            process.kill()
            process.wait(timeout=10)
            summary["terminatedOwnProbe"] = True
        summary["finalHost"] = memory()
        if samples:
            summary["minimumObservedHostFreeMiB"] = min(s["freeMiB"] for s in samples)
        (args.output / "samples.json").write_text(json.dumps(samples), encoding="utf-8")
        (args.output / "summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")
        print(json.dumps(summary, indent=2))
    if not summary["success"]:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
