<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../DeskNest.Core/DeskNest.Core.csproj" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.22.1" />
    <PackageReference Include="Tokenizers.HuggingFace" Version="3.23.1" />
  </ItemGroup>
</Project>
